# Generated by Django 5.0.7 on 2024-07-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketers',
            name='player_id',
        ),
    ]
