# Generated by Django 5.0.7 on 2024-07-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='AllUsers',
        ),
    ]
